language: shell

env:
- HOMEBREW_NO_INSTALL_CLEANUP=1

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
  - master

os: osx

before_install:
- brew update

script:
- brew audit *.rb
- brew install *.rb
- brew test *.rb
