name: Testing of Homebrew recipes

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  test:
    name: "Verify ${{ matrix.recipe }}"

    runs-on: macos-latest
    env: {HOMEBREW_NO_INSTALL_CLEANUP: 1}

    strategy:
      fail-fast: false
      matrix:
        recipe:
          - sass
          - migrator

    steps:
      - uses: actions/checkout@v3
      - run: brew update
      - run: brew tap-new sass/sass
      - run: brew --repository sass/sass
      - run: |
          path="$(brew --repository sass/sass)"
          rm -rf "$path"
          ln -s "$(pwd)" "$path"
      # TODO: Add --online once https://github.com/Homebrew/brew/pull/16626 is fixed
      - run: brew audit --strict --git sass/sass/${{ matrix.recipe }}
      - run: brew install sass/sass/${{ matrix.recipe }}
      - run: brew test sass/sass/${{ matrix.recipe }}
      - run: brew uninstall sass/sass/${{ matrix.recipe }}
