name: Testing of Homebrew recipes

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  test:
    name: "Verify ${{ matrix.recipe }}"

    runs-on: macos-latest
    env: {HOMEBREW_NO_INSTALL_CLEANUP: 1}

    strategy:
      fail-fast: false
      matrix:
        recipe:
          - sass@1.23.0-module.beta1.rb
          - sass.rb
          - migrator.rb

    steps:
      - uses: actions/checkout@v2
      - run: brew update
      - run: brew audit --strict --online $GITHUB_WORKSPACE/${{ matrix.recipe }}
      - run: brew install $GITHUB_WORKSPACE/${{ matrix.recipe }}
      - run: brew test $GITHUB_WORKSPACE/${{ matrix.recipe }}
      - run: brew uninstall $GITHUB_WORKSPACE/${{ matrix.recipe }}
